---
# tasks file for mysql_db
    - name: Install mysqldb
      apt: name={{ item }} state=latest
      with_items:
        - mysql-server
        - mysql-client
    - name: Start DB service
      command: service mysql restart
    - name: Create database
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: '{{ db_name }}'
        state: present
    - name: create DB user
      mysql_user:
        name: '{{ db_user }}'
        password: '{{ db_password }}'
        priv: '*.*:ALL'
        state: present
        host: '%'
